/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarkalarRouteImport } from './routes/markalar'
import { Route as IndexRouteImport } from './routes/index'

const MarkalarRoute = MarkalarRouteImport.update({
  id: '/markalar',
  path: '/markalar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/markalar': typeof MarkalarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/markalar': typeof MarkalarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/markalar': typeof MarkalarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/markalar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/markalar'
  id: '__root__' | '/' | '/markalar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarkalarRoute: typeof MarkalarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/markalar': {
      id: '/markalar'
      path: '/markalar'
      fullPath: '/markalar'
      preLoaderRoute: typeof MarkalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarkalarRoute: MarkalarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
